# Generated by Django 6.0 on 2026-01-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_site', '0002_rename_star_ideastar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='content',
        ),
    ]
