# Generated by Django 6.0 on 2026-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_site', '0005_idea_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtool',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devtool',
            name='kind',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
