# Generated by Django 6.0 on 2026-01-02 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_site', '0007_ideastar_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ideastar',
            name='unique_user_idea_star',
        ),
        migrations.AlterField(
            model_name='ideastar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ideastar',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('idea', 'session_key'), name='uniq_star_idea_session'),
        ),
        migrations.AddConstraint(
            model_name='ideastar',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('idea', 'user'), name='uniq_star_idea_user'),
        ),
    ]
