# Generated by Django 6.0 on 2025-12-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_created_at_remove_movie_date_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
