# Generated by Django 6.0 on 2026-01-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_site', '0003_remove_idea_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devtool',
            name='content',
        ),
        migrations.RemoveField(
            model_name='devtool',
            name='kind',
        ),
    ]
