# Generated by Django 6.0 on 2026-01-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_site', '0004_remove_devtool_content_remove_devtool_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
