# Generated by Django 6.0 on 2026-01-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_site', '0006_devtool_content_devtool_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideastar',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
